name: Qemu-gunyah release
run-name: Qemu-gunyah release
on: workflow_dispatch
#  push:
    # Sequence of patterns matched against refs/tags
#    tags:
#      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  apiLevel: 35
  ndkPath: "$HOME/android-ndk-r30-beta1"
  toolchain: "$HOME/android-ndk-r30-beta1/toolchains/llvm/prebuilt/linux-x86_64"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: 部署
      run: |
        sudo apt update
        sudo apt install -y build-essential ninja-build pkg-config xz-utils device-tree-compiler
        sudo pip3 install --upgrade meson
        wget https://dl.google.com/android/repository/android-ndk-r30-beta1-linux.zip -O ndk.zip
        unzip -q ndk.zip -d $HOME
        
    - name: apt update
      run: sudo apt update
        
    - name: run 1.sh
      run: sudo ./1.sh
      
    - name: run 2.sh
      run: sudo ./2.sh
      
    - name: Zip the Build
      run: zip -r ${{ secrets.ReleaseZipName }} .

    - name: 上传
      uses: actions/upload-artifact@v7
      with:
        name: qemu-gzvm
        path: qemu-gzvm.xz
        archive: false
        if-no-files-found: error
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          ${{ secrets.ReleaseZipName }}.zip
          LICENSE 
